name = "ui-events-app"
main = "functions/index.ts"
compatibility_date = "2023-05-15"

[build]
command = "pnpm build"

[vars]
# Environment variables
# Add your environment variables here

[env.development.vars]
# Development environment variables
NODE_ENV = "development"

[env.production.vars]
# Production environment variables
NODE_ENV = "production"

# Serve static assets from frontend/dist for non-/api routes
[site]
bucket = "./frontend/dist"

# Route configuration
[[routes]]
pattern = "/api/*"